### ISSUE TITLE
Manifest merger failed

### ISSUE THREAD

**Issue by wrjcs** [jpnurmi/dart_serial_port#1]
Hello,
I installed this package, but I have this error?

Manifest merger failed : Attribute application@label value=xxxxx from AndroidManifest.xml:21:9-33
  	is also present at [com.github.licheedev.Android-SerialPort-API:serialport:1.0.1] AndroidManifest.xml:13:9-41 value=(@string/app_name).
  	Suggestion: add 'tools:replace="android:label"' to <application> element at AndroidManifest.xml:19:5-56:19 to override.

how to resolve it?

Thanks.

**Comment by jpnurmi** [comment]
Hi, what is the relation to dart_serial_port?

**Comment by jpnurmi** [comment]
- https://github.com/BbsonLin/serial_port_flutter/issues/8
- https://github.com/BbsonLin/serial_port_flutter#issues
- https://github.com/BbsonLin/serial_port_flutter/commit/2ae93ef70b8a5897b47013af890c946da84b827f
