### ISSUE TITLE
Invalid argument(s): Failed to load dynamic library (126)

### ISSUE THREAD

**Issue by qian4427** [jpnurmi/dart_serial_port#11]
I know less some dll file,but I dont konw Where??some one HELP me?????

**Comment by jpnurmi** [comment]
Which platform? Have you tried [flutter_serial_port](https://github.com/jpnurmi/flutter_serial_port)?

**Comment by qian4427** [comment]
> Which platform? Have you tried [flutter_serial_port](https://github.com/jpnurmi/flutter_serial_port)?

thank you,  when i use flutter_serial_port  everything is ok ? thank you
