### ISSUE TITLE
productID and vendorId return random numbers

### ISSUE THREAD

**Issue by Coimbra1984** [jpnurmi/dart_serial_port#15]
I have a device which returns random numbers on productId. Debugging into it, the problem is that
`sp_get_port_usb_vid_pid`
returns an error for this device. The problem can be fixed with this PR: https://github.com/jpnurmi/dart_serial_port/pull/14

**Comment by jpnurmi** [comment]
Thanks for the fix! I'm planning to migrate to null safety without maintaining multiple branches, so I wanted to get the fix in before that. The fix has been published in v0.0.7: https://pub.dev/packages/dart_serial_port/versions/0.0.7
