### ISSUE TITLE
Deployment on Android

### ISSUE THREAD

**Issue by ayalma** [jpnurmi/dart_serial_port#2]
Invalid argument(s): Failed to load dynamic library (dlopen failed: library "libserialport.so" not found)
when try to use this lib in flutter android app

**Comment by jpnurmi** [comment]
Sorry, clear instructions are still missing. This package is using [libserialport](https://sigrok.org/wiki/Libserialport) via [dart:ffi](https://dart.dev/guides/libraries/c-interop), which means that `libserialport.so` needs to be bundled with the app. I need to investigate if it's possible for me to pre-build the library and somehow offer via platform specific extension packages.

Anyway, the process of building [libserialport](https://github.com/sigrokproject/libserialport) for Android:
- Download and install the [Android NDK](https://developer.android.com/ndk)
- Follow the [instructions for building Autoconf projects](https://developer.android.com/ndk/guides/other_build_systems#autoconf)
  - See also [Supported ABIs](https://developer.android.com/ndk/guides/abis#sa)

What kind of Android device are you using, by the way?

**Comment by jpnurmi** [comment]
I have written down some more detailed build instructions, and attached pre-built binaries as well: https://github.com/jpnurmi/dart_serial_port/wiki/Android.

**Comment by ayalma** [comment]
Thanks for you'r response
 let the issue be open . if you are agree  ?

**Comment by jpnurmi** [comment]
Sure, ideally it should work out of the box, of course. :) I'll try to figure out how to provide pre-built libraries from a Dart package, so that they will be automatically included into the application APK.

**Comment by jpnurmi** [comment]
I found out that the [flutter_ffmpeg](https://pub.dev/packages/flutter_ffmpeg) package has its Android dependency, a native library, listed in its [build.gradle](https://github.com/tanersener/flutter-ffmpeg/blob/master/android/build.gradle#L48). I'm not familiar with how this works, but apparently the Gradle dependency gets automatically fetched from [Maven repositories](https://mvnrepository.com/artifact/com.arthenica/mobile-ffmpeg-min).

**Comment by jpnurmi** [comment]
libserialport is a tiny C-library with just a few C-files to compile, but `dart_serial_port` is a pure Dart package so there's no way to compile C-code as part of it. However, Flutter's build system does have everything needed for building C-code as part of the platform plugins, so I have created a simple `flutter_serial_port` wrapper package that simply utilizes Flutter's build system to build libserialport under the hood. The package does not provide any additional API, it just exports dart_serial_port's API _and_ builds & deploys libserialport so that everything works "out of the box":

```
dependencies:
  flutter_serial_port:
    git: git://github.com/jpnurmi/flutter_serial_port.git
```

P.S. I was going to release it on pub.dev too, because such name didn't show up in search, but it turns out the name is taken by an old unlisted/discontinued package: https://pub.dev/packages/flutter_serial_port

**Comment by ayalma** [comment]
I installed you'r package on android and i get this error
F/libc    (15108): Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 15125 (1.ui)

**Comment by jpnurmi** [comment]
Can you inspect what is in the .apk? Looks perfect here:
```
$ unzip -v flutter_serial_port/example/build/app/outputs/apk/debug/app-debug.apk
Archive:  flutter_serial_port/example/build/app/outputs/apk/debug/app-debug.apk
 Length   Method    Size  Cmpr    Date    Time   CRC-32   Name
--------  ------  ------- ---- ---------- ----- --------  ----
[...]
  104280  Defl:N    27652  74% 1980-00-00 00:00 68a71818  lib/arm64-v8a/libserialport.so
23495304  Defl:N 10575073  55% 1980-00-00 00:00 969abcc2  lib/armeabi-v7a/libflutter.so
   87636  Defl:N    33454  62% 1980-00-00 00:00 a2517135  lib/armeabi-v7a/libserialport.so
28665728  Defl:N 11958139  58% 1980-00-00 00:00 341f76a7  lib/x86/libflutter.so
   99824  Defl:N    26753  73% 1980-00-00 00:00 27798649  lib/x86/libserialport.so
29421136  Defl:N 11959816  59% 1980-00-00 00:00 60ebfca7  lib/x86_64/libflutter.so
  104552  Defl:N    35873  66% 1980-00-00 00:00 bd03c07b  lib/x86_64/libserialport.so
[...]
--------          -------  ---                            -------
124207730         49702357  60%                            362 files
```

**Comment by ayalma** [comment]
That's my output
`
28275096  Defl:N 11476827  59% 00-00-1980 00:00 e7434781  lib/arm64-v8a/libflutter.so
  104280  Defl:N    27652  74% 00-00-1980 00:00 46d8632e  lib/arm64-v8a/libserialport.so
   87636  Defl:N    33471  62% 00-00-1980 00:00 b358adad  lib/armeabi-v7a/libserialport.so
28692344  Defl:N 11969470  58% 00-00-1980 00:00 9d7afa69  lib/x86/libflutter.so
   99824  Defl:N    26752  73% 00-00-1980 00:00 b06326b7  lib/x86/libserialport.so
29447200  Defl:N 11970418  59% 00-00-1980 00:00 b05065ee  lib/x86_64/libflutter.so
  104552  Defl:N    35873  66% 00-00-1980 00:00 2913eb60  lib/x86_64/libserialport.so
`

**Comment by jpnurmi** [comment]
Thanks, the output looks good. The libraries are there as appropriate.

For what it's worth, I have flashed Android 10 on a Raspberry Pi 4, and here's the `flutter_serial_port` example running on it:
![rpi](https://user-images.githubusercontent.com/140617/94442231-02501880-01a4-11eb-8702-1e7e405ed433.png)

**Comment by jpnurmi** [comment]
Is there any more info around/before the SIGSEGV? Is it possible to run it in a debugger to get a backtrace?

**Comment by firesh** [comment]
Here is a simple solution:
1. Make directory: `android/app/src/main/jniLibs`
2. Download libs: https://github.com/jpnurmi/dart_serial_port/wiki/libserialport-android.zip
3. unzip and copy to `android/app/src/main/jniLibs`

**Comment by jpnurmi** [comment]
There's also a simple wrapper package that builds and deploys libserialport using Flutter's build system: https://github.com/jpnurmi/flutter_serial_port
