### ISSUE TITLE
Could not load source 'dart:ffi-patch/ffi_dynamic_library_patch.dart': <source not available>.

### ISSUE THREAD

**Issue by goldencoder20** [jpnurmi/dart_serial_port#23]
please when try this simple example I get this error

example:

```
import 'package:dart_serial_port/dart_serial_port.dart';
void main() {
  print('Available ports:');
  var i = 0;
  for (final name in SerialPort.availablePorts) {
    final sp = SerialPort(name);
    print('${++i}) $name');
    print('\tDescription: ${sp.description}');
    print('\tManufacturer: ${sp.manufacturer}');
    print('\tSerial Number: ${sp.serialNumber}');
    print('\tProduct ID: 0x${sp.productId.toRadixString(16)}');
    print('\tVendor ID: 0x${sp.vendorId.toRadixString(16)}');
    sp.dispose();
  }
}
```

error:
```
Could not load source 'dart:ffi-patch/ffi_dynamic_library_patch.dart': <source not available>.
```

**Comment by jpnurmi** [comment]
Could you try with the latest Dart SDK and `dart_serial_port`?

**Comment by digitalkirkley** [comment]
On Linux desktop linux-arm64 (Ubunutu 20.10), Flutter 2.1.0-13.0.pre.104, Dart 2.13, I am getting a "failed to load dynamic library 'libserialport.so'".  I will try this on X86 but curious if you knew what the issue might be?  Thank you.

**Comment by jpnurmi** [comment]
>  Is this where you mention using the Flutter_Serial_Port so that it automatically packages and includes the required reference?

Yes, exactly. dart_serial_port is based on an external library that must be deployed in a way or another. flutter_serial_port can bundle it with the app, but on Linux it's also possible to install the distribution's libserialport package.

**Comment by Enhed** [comment]
@jpnurmi can u explain, how to add libserialport to windows app? flutter_serial_port is not working in flutter 2.0, cos without null safety

**Comment by Enhed** [comment]
i solved, need just add dependenci like that and not use them

flutter_serial_port:
    git: https://github.com/jpnurmi/flutter_serial_port

**Comment by jpnurmi** [comment]
Sorry for the confusion with `flutter_serial_port`. The package name didn't show up in pub.dev search results when I chose the name, because I hadn't realized to include discontinued packages. I've been hoping that the owner of the discontinued package would be willing to hand over the package name, but he's not answering me nor others who have tried, unfortunately.

**Comment by jpnurmi** [comment]
Presumably, the problem does not occur with stable FFI in Dart SDK 2.12.
