### ISSUE TITLE
Null pointer dereference on android

### ISSUE THREAD

**Issue by Coimbra1984** [jpnurmi/dart_serial_port#8]
Hi,

when I execute the following code:
`List<String> prts = SerialPort.availablePorts;`
my complete application crashes on android with the following output:

W/1.ui    (28235): type=1400 audit(0.0:63973): avc: denied { read } for uid=10327 name="tty" dev="sysfs" ino=13792 scontext=u:r:untrusted_app:s0:c71,c257,c512,c768 tcontext=u:object_r:sysfs:s0 tclass=dir permissive=0
F/libc    (28235): Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 28378 (1.ui), pid 28235 (mple.leakagepro)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'motorola/river_reteu_n/river_n:10/QPUS30.52-16-2-7-4/e7923d:user/release-keys'
Revision: 'PVT'
ABI: 'arm64'
Timestamp: 2020-12-16 08:48:33+0100
pid: 28235, tid: 28378, name: 1.ui  >>> com.example.leakagepro <<<
uid: 10327
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
Cause: null pointer dereference
    x0  0000000000000000  x1  00000078ee43a409  x2  0000000000000000  x3  0000000000000000
    x4  00000078dbd50c61  x5  00000078ee365581  x6  00000078ee3655d8  x7  0000000000000004
    x8  0000000000000007  x9  0000000000000000  x10 0000000000000003  x11 00000078c0000000
    x12 0000000000000a00  x13 00000000015c7f98  x14 0000000000000006  x15 00000078f375cdb0
    x16 00000078f3685000  x17 00000078ee365601  x18 00000078ed856000  x19 00000078dbccf7c0
    x20 000000794c756cf0  x21 000000794c756d00  x22 00000078f2808041  x23 00000078f0365b98
    x24 00000078ee365101  x25 00000078f3684000  x26 000000794c74d800  x27 00000078ee3650c0
    x28 0000000000000004  x29 00000078f375cdc8
    sp  00000078f3684000  lr  00000078dbcd03a8  pc  00000078dbcd017c
backtrace:
      #00 pc 000000000005017c  <anonymous:78dbc80000>
Lost connection to device.

**Comment by Coimbra1984** [comment]
Ok, I could debug the problem. Happens, because the reutrn value of sp_list_ports isn't checked. In my case it returned -2 (because of PERMISSION denied) which leads to a corrupt out variable I guess. I fixed it, see pull request https://github.com/jpnurmi/dart_serial_port/pull/9

**Comment by jpnurmi** [comment]
Thanks again for the fix!
